name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Instalar dependências (MUITO IMPORTANTE: sem isso o build falha)
      - name: Install Dependencies
        run: npm ci
        working-directory: web

      # 2. Rodar o Build (Direcionando para a pasta web)
      - name: Build Project
        run: npm run build
        working-directory: web

      # 3. Deploy para o Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_FULL_STACK_A32EB }}"
          channelId: live
          projectId: project-full-stack-a32eb
